version: "3"
services:
  school:
    image: vumatel/infrastructure:latest
    volumes:
      - ~/.ssh:/root/.ssh # map ssh keys
    command: ansible-playbook /code/swarm.yml  -i /etc/ansible/inventory --vault-password-file=/code/.vault.key --tags=authenticationservice --limit=${ENV} --skip-tags=postgres
    environment:
      - ANSIBLE_HOST_KEY_CHECKING=False
      - ANSIBLE_LIBRARY=/etc/ansible/library
