version: "3"
services:
  web:
    restart: on-failure:10
    build: .
    command: sh /code/run.sh
    volumes:
      - .:/code
    ports:
      - "8000:80"
    links:
      - redis
    env_file:
      - env.dev

  redis:
    image: redis:alpine